<a href="https://colab.research.google.com/github/princeyadav72489-lab/Shopping-dataset-analysis/blob/main/Shopping_Dataset_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip -q install kagglehub

import kagglehub

path = kagglehub.dataset_download("anvitkumar/shopping-dataset")

print("Dataset Path:", path)

Downloading to /root/.cache/kagglehub/datasets/anvitkumar/shopping-dataset/466.archive...

100%|██████████| 1.22M/1.22M [00:00<00:00, 126MB/s]

Extracting files...
Dataset Path: /root/.cache/kagglehub/datasets/anvitkumar/shopping-dataset/versions/466

In [2]:
import os

for root, dirs, files in os.walk(path):
    for file in files:
        print(file)

face-moisturisers.csv
sweaters.csv
saree-blouse.csv
skirts.csv
earrings.csv
chair-cover.csv
scarves.csv
wall-art.csv
swim-tops.csv
shirts.csv
bathroom-accessories.csv
mangalsutra.csv
bath-towels.csv
briefs.csv
dresses.csv
jumpsuit.csv
face-wash-and-cleanser.csv
handbags.csv
boxers.csv
runners.csv
hair-accessory.csv
hair-masks.csv
track-pants.csv
backpacks.csv
hair-cream-and-mask.csv
perfume-and-body-mist.csv
dupatta.csv
trousers.csv
jeans.csv
caps.csv
tunics.csv
hair-brush-and-comb.csv
kurtas.csv
tshirts.csv
home-fragrance-set.csv
palazzos.csv
bodysuit.csv
bra.csv
duffel-bag.csv
sherwani.csv
jackets.csv
sarees.csv
showpieces.csv
sunglasses.csv
thermal-bottoms.csv
night-suits.csv
shaving-essentials.csv
headphones.csv
kurta-sets.csv
pillow-covers.csv
flip-flops.csv
co-ords.csv
casual-shoes.csv
sandals.csv
clutches.csv
belts.csv
yoga-mats.csv
bracelet.csv
lipstick.csv
mobile-accessories.csv
clothing-set.csv
Combined_dataset.csv
bedsheets.csv
wallets.csv
nightdress.csv
sweatshirts.csv
floor-mats--dhurries.csv
ring.csv
ethnic-dresses.csv
dinnerware.csv
tights.csv
shampoo-and-conditioner.csv
tops.csv
lounge-shorts.csv
formal-shoes.csv
outdoor-masks.csv
kurtis.csv
lounge-tshirts.csv
boots.csv
heels.csv
lounge-pants.csv
candle-holders.csv
towel-set.csv
trunk.csv
dungarees.csv
README.md
bath-robe.csv
shorts.csv
sports-shoes.csv
trolley-bag.csv
flats.csv
table-covers.csv
watches.csv
foundation.csv
cutlery.csv
camisoles.csv
innerwear-vests.csv
gloves.csv
curtains-and-sheers.csv

In [3]:
import pandas as pd
import os

csv_file = os.path.join(path, "Combined_dataset.csv")

df = pd.read_csv(csv_file)

df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [4]:
print(df.columns.tolist())

['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

In [5]:
import pandas as pd
import os

csv_file = os.path.join(path, "Combined_dataset.csv")
df = pd.read_csv(csv_file)

df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [6]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nFirst 5 Rows:")
display(df.head())

print("\nLast 5 Rows:")
display(df.tail())

Shape: (1000, 24)

Columns:
['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

Data Types:
product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

First 5 Rows:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

Last 5 Rows:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [7]:
print(df.isnull().sum())

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [8]:
df = df.dropna()

print("New Shape:", df.shape)

New Shape: (10, 24)

In [9]:
high_rated = df[df["rating"] > 4]

display(high_rated.head())

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
418,18689340,Flying Machine,Women Black Wide Leg High-Rise Light Fade Crop...,4.3,36,2349,42.0,"""₹1,362.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":3,""2_stars"":2,""3_stars"":1,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",ARV███ LI███TYL█████████LIM██████,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-18689340_cae700""]",10T███LOO███DU █████████ITY███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
752,18241626,Roadster,The Lifestyle Co. Women Maroon & Black Ribbed...,4.5,25,1699,62.0,"""₹645.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":4,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""36.0in"",""value_name"":""B...","[""https://videos.myntassets.com/assets/videos/...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
754,18241644,Roadster,The Lifestyle Co. Women Pink Acrylic Pullover,4.3,55,1999,62.0,"""₹759.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":3,""4_stars"":...","[{""percentage"":""50"",""value_name"":""Fit, Just Ri...",Tru███t C███erc███,"[{""size"":""XS"",""value"":""38.0in"",""value_name"":""B...","[""rw-18241644_cae700"",""https://videos.myntasse...",1 s███loo███Cab█████████-01███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
755,18240570,all about you,Women Navy Blue & Red Checked Pullover,4.3,53,2499,65.0,"""₹874.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":4,""4_stars"":...","[{""percentage"":""67"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""rw-18240570_cae700""]",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters
756,18240582,all about you,Women Maroon Cable Knit Pullover,4.4,39,2499,65.0,"""₹874.00""",INR,http://assets.myntassets.com/assets/images/182...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...","[{""percentage"":""80"",""value_name"":""Fit, A Littl...",Vis███ St███,"[{""size"":""S"",""value"":""34.0in"",""value_name"":""To...","[""https://videos.myntassets.com/assets/videos/...",3rd███oor███o. █████████Mai███████████████████...,[{}],"{""applicable_on"":""Orders above Rs. 999 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",sweaters

In [10]:
selected_columns = df[["title", "category", "rating", "final_price"]]

display(selected_columns.head())

              title  category  rating  final_price
418  Flying Machine     jeans     4.3  "₹1,362.00"
752        Roadster  sweaters     4.5    "₹645.00"
753        Roadster  sweaters     3.8    "₹944.00"
754        Roadster  sweaters     4.3    "₹759.00"
755   all about you  sweaters     4.3    "₹874.00"

In [11]:
print("Duplicates Before:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates After:", df.duplicated().sum())

Duplicates Before: 0
Duplicates After: 0

In [14]:
df["quantity"] = 1
df["total_amount"] = df["final_price"] * df["quantity"]

display(df[["title", "final_price", "quantity", "total_amount"]].head())

              title  final_price  quantity total_amount
418  Flying Machine  "₹1,362.00"         1  "₹1,362.00"
752        Roadster    "₹645.00"         1    "₹645.00"
753        Roadster    "₹944.00"         1    "₹944.00"
754        Roadster    "₹759.00"         1    "₹759.00"
755   all about you    "₹874.00"         1    "₹874.00"

In [15]:
df.to_csv("cleaned_shopping_dataset.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [16]:
print("""
SUMMARY

1. Loaded Combined_dataset.csv into Pandas.
2. Explored dataset structure, columns, and data types.
3. Identified and handled missing values using dropna().
4. Filtered products with rating greater than 4.
5. Selected important columns for analysis.
6. Removed duplicate records.
7. Created a derived column 'total_amount'.
8. Saved the cleaned dataset as cleaned_shopping_dataset.csv.
""")

SUMMARY

1. Loaded Combined_dataset.csv into Pandas.
2. Explored dataset structure, columns, and data types.
3. Identified and handled missing values using dropna().
4. Filtered products with rating greater than 4.
5. Selected important columns for analysis.
6. Removed duplicate records.
7. Created a derived column 'total_amount'.
8. Saved the cleaned dataset as cleaned_shopping_dataset.csv.